Get http://localhost:3000/api/users

###

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
  "username": "first",
  "email": "first@example.com",
  "password": "first123",
  "firstName": "first",
  "lastName": "last"
}
###

PATCH  http://localhost:3000/api/users/67e6dd82f972bbf6bf76f8c2 HTTP/1.1
content-type: application/json

{
  "username": "first-update",
  "email": "first-update@example.com"
}


###
Get http://localhost:3000/api/users/67e6dd82f972bbf6bf76f8c2

###
DELETE http://localhost:3000/api/users/67e6cdb77ea5db86154c95e4